version: '3.8'

services:
  compiler:
    build: .
    container_name: online-judge-compiler
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
    volumes:
      - compiler_tmp:/app/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /app/tmp:noexec,nosuid,size=100m

volumes:
  compiler_tmp:
    driver: local 